from aiogram import Router, F
from aiogram.types import (
    Message,
    MessageReactionUpdated,
    FSInputFile,
    InlineKeyboardMarkup,
    InlineKeyboardButton,
    CallbackQuery,
)
from aiogram.filters import Command
from aiogram import Bot
from ..services.history import history_manager
from ..services.llm import MemeBrain
from ..services.search import ImageSearcher
from ..services.image_gen import MemeGenerator
from ..services.jokes import JokeService
from ..services.config import config
import os
import html
import asyncio
import logging
import random
import time
from typing import List, Optional

router = Router()

_generation_semaphore: Optional[tuple[asyncio.AbstractEventLoop, asyncio.Semaphore]] = None
_chat_locks: dict[int, tuple[asyncio.AbstractEventLoop, asyncio.Lock]] = {}
_last_auto_joke_at: dict[int, float] = {}

# Инициализация всех сервисов
meme_brain = MemeBrain()
image_searcher = ImageSearcher()
meme_generator = MemeGenerator()
joke_service = JokeService()

# Эмодзи, на которые реагируем, и их смысловое значение
MEME_TRIGGERS = {
    "👍": "Одобрение, класс, лайк",
    "👎": "Осуждение, дизлайк, плохо",
    "❤": "Любовь, очень нравится",
    "🔥": "Офигеть как круто, огонь, жара",
    "🥰": "Милота, обожание",
    "👏": "Аплодисменты, браво, поддержка",
    "😁": "Смешно, радость, ухмылка",
    "🤔": "Задумался, сомнение, подозрение",
    "🤯": "Взрыв мозга, шок, невероятно",
    "😱": "Испуг, шок, ужас",
    "🤬": "Злость, ярость, маты",
    "😢": "Грусть, печаль, слезы",
    "🎉": "Праздник, поздравление, радость",
    "🤩": "Восхищение, звезды в глазах",
    "🤮": "Тошнота, отвращение, гадость",
    "💩": "Дерьмо, очень плохо, ирония",
    "🤡": "Клоунада, глупость, ирония над автором"
}

def is_trigger_emoji(reaction_type) -> bool:
    """Проверяет, является ли эмодзи триггером для создания мема."""
    return hasattr(reaction_type, "emoji") and reaction_type.emoji in MEME_TRIGGERS

async def _show_chat_action(bot_instance: Bot, chat_id: int) -> None:
    """Отправляет в чат статус 'typing' (печать сообщения)."""
    try:
        await bot_instance.send_chat_action(chat_id, 'typing')
    except Exception as e:
        logging.error("Не удалось отправить chat action: %s", e)

async def _generate_meme_idea(
    context_messages: List[str], triggered_text: str, reaction_context: Optional[str]
) -> Optional[dict]:
    """Генерирует идею мема через LLM в отдельном потоке."""
    return await asyncio.to_thread(
        meme_brain.generate_meme_idea, context_messages, triggered_text, reaction_context
    )

async def _find_meme_template(query: str) -> Optional[str]:
    """Ищет URL шаблона мема в отдельном потоке."""
    return await asyncio.to_thread(image_searcher.search_template, query + " meme template")

async def _create_meme_file(
    template_url: str, top_text: str, bottom_text: str, chat_id: int, reply_to_message_id: Optional[int]
) -> Optional[str]:
    """Генерирует мем (скачивает шаблон и накладывает текст) в отдельном потоке."""
    unique_output_file = f"temp_meme_{chat_id}_{reply_to_message_id}.jpg"
    return await asyncio.to_thread(
        meme_generator.create_meme,
        image_url=template_url,
        top_text=top_text,
        bottom_text=bottom_text,
        output_path=unique_output_file
    )


def _get_generation_semaphore() -> asyncio.Semaphore:
    """Возвращает (и лениво создает) глобальный семафор генераций для текущего event loop."""
    global _generation_semaphore
    loop = asyncio.get_running_loop()

    if _generation_semaphore is None or _generation_semaphore[0] is not loop:
        max_concurrent = max(1, int(config.MAX_CONCURRENT_GENERATIONS))
        _generation_semaphore = (loop, asyncio.Semaphore(max_concurrent))

    return _generation_semaphore[1]


def _get_chat_lock(chat_id: int) -> asyncio.Lock:
    """Возвращает lock для конкретного чата (debounce от параллельных запросов) в текущем event loop."""
    loop = asyncio.get_running_loop()
    entry = _chat_locks.get(chat_id)

    if entry is None or entry[0] is not loop:
        entry = (loop, asyncio.Lock())
        _chat_locks[chat_id] = entry

    return entry[1]


async def _send_meme_photo(
    bot_instance: Bot,
    chat_id: int,
    photo_path: str,
    top_text: str,
    bottom_text: str,
    trigger_emoji: Optional[str],
    reply_to_message_id: Optional[int]
) -> None:
    """Отправляет готовое изображение мема в Telegram."""
    generator_tag = f"generated by {trigger_emoji}" if trigger_emoji else "generated by meme bot"
    caption_text = (
        f"🤡 <b>{html.escape(top_text)}</b>\n"
        f"{html.escape(bottom_text)}\n\n"
        f"<i>({generator_tag})</i>"
    )

    await bot_instance.send_photo(
        chat_id=chat_id,
        photo=FSInputFile(photo_path),
        caption=caption_text,
        parse_mode='HTML',
        reply_to_message_id=reply_to_message_id
    )

async def generate_and_send_meme(
    chat_id: int,
    triggered_text: str,
    context_messages: List[str],
    reaction_context: Optional[str] = None,
    reply_to_message_id: Optional[int] = None,
    bot_instance: Optional[Bot] = None,
    trigger_emoji: Optional[str] = None
) -> None:
    """
    Основная логика генерации и отправки мема.
    Декомпозирована на вспомогательные функции для читаемости и тестирования.
    """
    if not bot_instance:
        logging.error("bot_instance обязателен для generate_and_send_meme")
        return
    
    if not triggered_text or not triggered_text.strip():
        logging.warning("Пропуск генерации мема: триггерный текст пуст")
        return
    
    if not context_messages:
        logging.warning("Пропуск генерации мема: контекст сообщений пуст")
        return
    
    chat_lock = _get_chat_lock(chat_id)
    semaphore = _get_generation_semaphore()

    async with chat_lock:
        async with semaphore:
            # 1. Показываем активность бота
            await _show_chat_action(bot_instance, chat_id)

            # 2. LLM: Генерация идеи мема
            meme_idea = await _generate_meme_idea(context_messages, triggered_text, reaction_context)

            if not meme_idea:
                logging.error("❌ ОШИБКА: LLM вернула пустоту.")
                await bot_instance.send_message(
                    chat_id, "Мозги сломались, слишком сложно!", reply_to_message_id=reply_to_message_id
                )
                return

            if not meme_idea.get('is_memable'):
                logging.warning("⚠️ ОТКАЗ: Нейросеть решила, что контекст не смешной для мема.")
                return

            logging.info("✅ Идея сгенерирована: %s / %s", meme_idea.get('top_text'), meme_idea.get('bottom_text'))

            # 3. Поиск шаблона
            query = meme_idea['search_query']
            template_url = await _find_meme_template(query)

            if not template_url:
                await bot_instance.send_message(
                    chat_id,
                    f"🎨 <b>Шаблон не найден!</b>\n\n"
                    f"Я не смог найти подходящую картинку по запросу: <i>{html.escape(query)}</i>.",
                    parse_mode='HTML',
                    reply_to_message_id=reply_to_message_id
                )
                return

            # 4. Генерация мема
            final_image_path = await _create_meme_file(
                template_url, meme_idea['top_text'], meme_idea['bottom_text'], chat_id, reply_to_message_id
            )

            if not final_image_path:
                await bot_instance.send_message(
                    chat_id, "Не удалось создать картинку из шаблона.", reply_to_message_id=reply_to_message_id
                )
                return

            # 5. Отправка результата
            try:
                await _send_meme_photo(
                    bot_instance=bot_instance,
                    chat_id=chat_id,
                    photo_path=final_image_path,
                    top_text=meme_idea['top_text'],
                    bottom_text=meme_idea['bottom_text'],
                    trigger_emoji=trigger_emoji,
                    reply_to_message_id=reply_to_message_id
                )
            except Exception as e:
                logging.error("Ошибка при отправке фото: %s", e)
                try:
                    await bot_instance.send_message(
                        chat_id, "Ошибка отправки мема.", reply_to_message_id=reply_to_message_id
                    )
                except Exception as nested_e:
                    logging.error("Не удалось отправить сообщение об ошибке: %s", nested_e)
            finally:
                # Очистка временного файла
                if os.path.exists(final_image_path):
                    try:
                        os.remove(final_image_path)
                    except Exception as e:
                        logging.error("Не удалось удалить временный файл %s: %s", final_image_path, e)


# Хендлер для реакций
@router.message_reaction(F.new_reaction.contains(is_trigger_emoji))
async def reaction_handler(reaction: MessageReactionUpdated):
    """Срабатывает при получении одной из триггерных реакций."""
    chat_id = reaction.chat.id
    trigger_emoji = reaction.new_reaction[0].emoji
    reaction_meaning = MEME_TRIGGERS.get(trigger_emoji)
    
    if not reaction_meaning:
        logging.warning("Неизвестный эмодзи-триггер: %s", trigger_emoji)
        return

    context_messages = history_manager.get_context(chat_id, reaction.message_id)
    if not context_messages:
        return

    triggered_text = history_manager.get_message_text(chat_id, reaction.message_id)

    if not triggered_text:
        try:
            await reaction.bot.send_message(
                chat_id,
                "🧐 <b>Я не вижу это сообщение!</b>\n\n"
                "Я могу делать мемы только из сообщений, которые пришли, пока я был онлайн.",
                parse_mode='HTML'
            )
        except Exception as e:
            logging.error("Не удалось отправить сообщение об ошибке истории: %s", e)
        return

    await generate_and_send_meme(
        chat_id=chat_id,
        triggered_text=triggered_text,
        context_messages=context_messages,
        reaction_context=reaction_meaning,
        reply_to_message_id=reaction.message_id,
        bot_instance=reaction.bot,
        trigger_emoji=trigger_emoji
    )


# Хендлер для текстовых сообщений
@router.message(F.text)
async def message_handler(message: Message):
    """
    Слушает все текстовые сообщения.
    1. Сохраняет их в историю.
    2. В личных сообщениях автоматически генерирует мем.
    """
    if message.text and message.text.strip():
        history_manager.add_message(message)
    else:
        return

    # Логика для Личных Сообщений (DM)
    if message.chat.type == 'private' and not message.text.startswith('/'):
        status_msg = await message.answer("🎨 Придумываю мем...")

        context_messages = history_manager.get_context(message.chat.id, message.message_id)
        
        if not context_messages:
            try:
                await status_msg.delete()
            except Exception:
                pass
            return

        dm_context = "Пользователь написал это сообщение в личном чате. Сделай мем, который иронично обыгрывает этот текст."

        await generate_and_send_meme(
            chat_id=message.chat.id,
            triggered_text=message.text,
            context_messages=context_messages,
            reaction_context=dm_context,
            reply_to_message_id=message.message_id,
            bot_instance=message.bot
        )

        try:
            await status_msg.delete()
        except Exception:
            pass


@router.message(Command("joke"))
async def command_joke_handler(message: Message):
    """Отправляет случайный анекдот с anekdot.ru + кнопки фидбека."""
    joke = await asyncio.to_thread(joke_service.get_joke)
    if not joke:
        await message.answer(
            "😕 <b>Анекдот не найден</b>\n\nПопробуй чуть позже.",
            parse_mode='HTML'
        )
        return

    keyboard = InlineKeyboardMarkup(
        inline_keyboard=[[
            InlineKeyboardButton(text="👍 Зашло", callback_data="joke_feedback:up"),
            InlineKeyboardButton(text="👎 Мимо", callback_data="joke_feedback:down"),
        ]]
    )

    sent = await message.answer(
        f"😂 <b>{html.escape(joke.title)}</b>\n\n{html.escape(joke.text)}",
        parse_mode='HTML',
        reply_markup=keyboard,
    )
    joke_service.bind_sent_message(sent.message_id, joke)


@router.callback_query(F.data.startswith("joke_feedback:"))
async def joke_feedback_handler(callback: CallbackQuery):
    """Собирает фидбек по анекдоту и влияет на будущую выдачу."""
    if not callback.message:
        await callback.answer("Нет сообщения для оценки", show_alert=False)
        return

    liked = callback.data.endswith(":up")
    ok = joke_service.vote(callback.message.message_id, liked)

    if not ok:
        await callback.answer("Не нашёл исходный анекдот", show_alert=False)
        return

    text = "Учту 👍" if liked else "Принял, будем реже такое слать 👎"
    await callback.answer(text, show_alert=False)


def _should_send_auto_joke(chat_id: int) -> bool:
    """Решает, отправлять ли авто-анекдот в группе (cooldown + chance)."""
    now = time.time()
    cooldown = max(0, int(config.JOKE_AUTO_COOLDOWN_SECONDS))
    chance = min(1.0, max(0.0, float(config.JOKE_AUTO_CHANCE)))

    last_at = _last_auto_joke_at.get(chat_id, 0.0)
    if now - last_at < cooldown:
        return False

    if random.random() > chance:
        return False

    _last_auto_joke_at[chat_id] = now
    return True


async def _send_joke_to_chat(message: Message, auto_mode: bool = False) -> None:
    """Общая логика отправки анекдота в чат."""
    joke = await asyncio.to_thread(joke_service.get_joke)
    if not joke:
        if not auto_mode:
            await message.answer(
                "😕 <b>Анекдот не найден</b>\n\nПопробуй чуть позже.",
                parse_mode='HTML'
            )
        return

    keyboard = InlineKeyboardMarkup(
        inline_keyboard=[[
            InlineKeyboardButton(text="👍 Зашло", callback_data="joke_feedback:up"),
            InlineKeyboardButton(text="👎 Мимо", callback_data="joke_feedback:down"),
        ]]
    )

    prefix = "🎲 Авто-анекдот" if auto_mode else "😂"
    sent = await message.answer(
        f"{prefix} <b>{html.escape(joke.title)}</b>\n\n{html.escape(joke.text)}",
        parse_mode='HTML',
        reply_markup=keyboard,
    )
    joke_service.bind_sent_message(sent.message_id, joke)


# Команда /help
@router.message(Command("help"))
async def command_help_handler(message: Message):
    """Справка по использованию бота."""
    triggers_list = list(MEME_TRIGGERS.keys())
    triggers_str = ", ".join(triggers_list[:10]) + "..."

    help_text = (
        "🎨 <b>Как пользоваться ботом</b>\n\n"
        "Я превращаю ваши сообщения в мемы! Вот как это работает:\n\n"
        f"1. <b>Реакция</b>: Поставьте реакцию ({triggers_str}) на любое сообщение.\n"
        "2. <b>Личка</b>: Просто напиши мне сообщение, и я сделаю из него мем.\n"
        "3. <b>/joke</b>: Случайный анекдот с anekdot.ru + оценка 👍/👎.\n"
        "4. <b>Контекст</b>: Я читаю диалог, чтобы мем был в тему.\n\n"
        "<i>Совет: Добавьте меня в группу, там веселее!</i>"
    )
    await message.answer(help_text, parse_mode='HTML')


# Команда /start
@router.message(Command("start"))
async def command_start_handler(message: Message):
    """Ответ на команду /start."""
    welcome_text = (
        "👋 <b>Привет! Я бот-мемогенератор.</b>\n\n"
        "Добавь меня в чат и ставь реакции на сообщения.\n"
        "Или просто пиши мне сюда — я сделаю мем из твоего текста!\n\n"
        "Нажми /help для подробностей!"
    )
    await message.answer(welcome_text, parse_mode='HTML')


# Команда /memory_stats
@router.message(Command("memory_stats"))
async def command_memory_stats_handler(message: Message):
    """Показывает статистику агентской памяти."""
    stats = history_manager.get_memory_statistics()
    
    if not stats.get('enabled'):
        await message.answer(
            "📝 <b>Агентская память отключена</b>\n\n"
            "Память не сохраняется между перезапусками.",
            parse_mode='HTML'
        )
        return
    
    stats_text = (
        f"📊 <b>Статистика агентской памяти</b>\n\n"
        f"💬 <b>Чатов в памяти:</b> {stats.get('total_chats', 0)}\n"
        f"📝 <b>Всего сообщений:</b> {stats.get('total_messages', 0)}\n"
        f"🗂 <b>ID чатов:</b> {', '.join(map(str, stats.get('chat_ids', []))[:5])}"
    )
    
    if len(stats.get('chat_ids', [])) > 5:
        stats_text += f"... (+{len(stats['chat_ids']) - 5} еще)"
    
    await message.answer(stats_text, parse_mode='HTML')


# Команда /clear_memory
@router.message(Command("clear_memory"))
async def command_clear_memory_handler(message: Message):
    """Очищает историю текущего чата из памяти."""
    chat_id = message.chat.id
    
    if chat_id not in history_manager.history or len(history_manager.history[chat_id]) == 0:
        await message.answer(
            "🤷‍♂️ <b>История пуста</b>\n\n"
            "В этом чате нет сохраненных сообщений.",
            parse_mode='HTML'
        )
        return
    
    message_count = len(history_manager.history[chat_id])
    history_manager.history[chat_id].clear()
    
    if history_manager.memory_enabled:
        from ..services.agent_memory import agent_memory
        agent_memory.clear_chat(chat_id)
    
    await message.answer(
        f"🗑 <b>История очищена!</b>\n\n"
        f"Удалено {message_count} сообщений из памяти этого чата.",
        parse_mode='HTML'
    )
